insert into review(comment, rating, course_id) values("Liked it!", 0, 1);
insert into review(comment, rating, course_id) values("Can be better", 3, 1);
insert into review(comment, rating, course_id) values("Can be better", 1, 1);
insert into review(comment, rating, course_id) values("Can be better", 1, 2);
insert into review(comment, rating, course_id) values("Liked it!", 0, 2);
insert into review(comment, rating, course_id) values("Best Course", 1, 2);
insert into review(comment, rating, course_id) values("Average", 0, 3);
insert into review(comment, rating, course_id) values("Good", 1, 3);
insert into review(comment, rating, course_id) values("Loved it!!", 3, 3);
insert into review(comment, rating, course_id) values("Average", 3, 4);
insert into review(comment, rating, course_id) values("Can be better", 4, 4);
insert into review(comment, rating, course_id) values("Liked it!", 0, 4);
insert into review(comment, rating, course_id) values("Can be better", 2, 5);
insert into review(comment, rating, course_id) values("Good", 1, 5);
insert into review(comment, rating, course_id) values("Loved it!!", 5, 5);
insert into review(comment, rating, course_id) values("Loved it!!", 0, 6);
insert into review(comment, rating, course_id) values("Can be better", 0, 6);
insert into review(comment, rating, course_id) values("Average", 5, 6);
insert into review(comment, rating, course_id) values("Can be better", 3, 7);
insert into review(comment, rating, course_id) values("Bad", 0, 7);
insert into review(comment, rating, course_id) values("Best Course", 4, 7);
insert into review(comment, rating, course_id) values("Loved it!!", 0, 8);
insert into review(comment, rating, course_id) values("Good", 0, 8);
insert into review(comment, rating, course_id) values("Bad", 3, 8);
insert into review(comment, rating, course_id) values("Average", 1, 9);
insert into review(comment, rating, course_id) values("Bad", 5, 9);
insert into review(comment, rating, course_id) values("Bad", 1, 9);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 0, 10);
insert into review(comment, rating, course_id) values("Can be better", 4, 10);
insert into review(comment, rating, course_id) values("Good", 3, 10);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 2, 11);
insert into review(comment, rating, course_id) values("Liked it!", 3, 11);
insert into review(comment, rating, course_id) values("Liked it!", 3, 11);
insert into review(comment, rating, course_id) values("Liked it!", 3, 12);
insert into review(comment, rating, course_id) values("Good", 1, 12);
insert into review(comment, rating, course_id) values("Can be better", 3, 12);
insert into review(comment, rating, course_id) values("Liked it!", 3, 13);
insert into review(comment, rating, course_id) values("Liked it!", 4, 13);
insert into review(comment, rating, course_id) values("Average", 2, 13);
insert into review(comment, rating, course_id) values("Can be better", 1, 14);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 1, 14);
insert into review(comment, rating, course_id) values("Average", 5, 14);
insert into review(comment, rating, course_id) values("Good", 3, 15);
insert into review(comment, rating, course_id) values("Average", 2, 15);
insert into review(comment, rating, course_id) values("Best Course", 2, 15);
insert into review(comment, rating, course_id) values("Bad", 1, 16);
insert into review(comment, rating, course_id) values("Liked it!", 2, 16);
insert into review(comment, rating, course_id) values("Liked it!", 2, 16);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 4, 17);
insert into review(comment, rating, course_id) values("Can be better", 1, 17);
insert into review(comment, rating, course_id) values("Good", 3, 17);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 4, 18);
insert into review(comment, rating, course_id) values("Bad", 3, 18);
insert into review(comment, rating, course_id) values("Liked it!", 3, 18);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 5, 19);
insert into review(comment, rating, course_id) values("Loved it!!", 2, 19);
insert into review(comment, rating, course_id) values("Average", 1, 19);
insert into review(comment, rating, course_id) values("Average", 5, 20);
insert into review(comment, rating, course_id) values("Liked it!", 0, 20);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 2, 20);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 2, 21);
insert into review(comment, rating, course_id) values("Loved it!!", 3, 21);
insert into review(comment, rating, course_id) values("Bad", 1, 21);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 5, 22);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 1, 22);
insert into review(comment, rating, course_id) values("Average", 2, 22);
insert into review(comment, rating, course_id) values("Bad", 0, 23);
insert into review(comment, rating, course_id) values("Best Course", 4, 23);
insert into review(comment, rating, course_id) values("Can be better", 3, 23);
insert into review(comment, rating, course_id) values("Loved it!!", 2, 24);
insert into review(comment, rating, course_id) values("Average", 0, 24);
insert into review(comment, rating, course_id) values("Bad", 1, 24);
insert into review(comment, rating, course_id) values("Bad", 2, 25);
insert into review(comment, rating, course_id) values("Good", 5, 25);
insert into review(comment, rating, course_id) values("Average", 4, 25);
insert into review(comment, rating, course_id) values("Can be better", 1, 26);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 4, 26);
insert into review(comment, rating, course_id) values("Bad", 4, 26);
insert into review(comment, rating, course_id) values("Can be better", 0, 27);
insert into review(comment, rating, course_id) values("Good", 5, 27);
insert into review(comment, rating, course_id) values("Best Course", 5, 27);
insert into review(comment, rating, course_id) values("Liked it!", 4, 28);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 0, 28);
insert into review(comment, rating, course_id) values("Average", 4, 28);
insert into review(comment, rating, course_id) values("Loved it!!", 0, 29);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 4, 29);
insert into review(comment, rating, course_id) values("Best Course", 1, 29);
insert into review(comment, rating, course_id) values("Loved it!!", 3, 30);
insert into review(comment, rating, course_id) values("Best Course", 5, 30);
insert into review(comment, rating, course_id) values("Average", 2, 30);
insert into review(comment, rating, course_id) values("Loved it!!", 4, 31);
insert into review(comment, rating, course_id) values("Best Course", 2, 31);
insert into review(comment, rating, course_id) values("Liked it!", 3, 31);
insert into review(comment, rating, course_id) values("Liked it!", 0, 32);
insert into review(comment, rating, course_id) values("Best Course", 2, 32);
insert into review(comment, rating, course_id) values("Will suggest to a friend", 3, 32);
