insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ALDA", "Analytics of data and Data pre-processing", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 1, 'Active', 'CSC', 'CSC 501', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("DAA", "Design and Analysis of Algorithms", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 1, 'Active', 'CSC', 'CSC 502', 3, 100, 91);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("CG", "Computer Graphics", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 2, 'Active', 'CSC', 'CSC 503', 3, 100, 85);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("AI", "Artificial Intelligence", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 2, 'Active', 'CSC', 'CSC 504', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ML", "Machine Learning", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 3, 'Active', 'CSC', 'CSC 505', 3, 100, 23);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("OS", "Operating Systems", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 3, 'Active', 'CSC', 'CSC 506', 3, 100, 11);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("DBMS", "Database Systems", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 4, 'Active', 'CSC', 'CSC 507', 3, 100, 71);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("SE", "Software Engineering", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 4, 'Active', 'CSC', 'CSC 508', 3, 100, 10);


insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ALDA1", "Analytics of data and Data pre-processing", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 5, 'Active', 'IT', 'IT 501', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("DAA1", "Design and Analysis of Algorithms", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 5, 'Active', 'IT', 'IT 502', 3, 100, 91);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("CG1", "Computer Graphics", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 6, 'Active', 'IT', 'IT 503', 3, 100, 85);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("AI1", "Artificial Intelligence", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 6, 'Active', 'IT', 'IT 504', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ML1", "Machine Learning", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 7, 'Active', 'IT', 'IT 505', 3, 100, 23);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("OS1", "Operating Systems", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 7, 'Active', 'IT', 'IT 506', 3, 100, 11);


insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ALDA2", "Analytics of data and Data pre-processing", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 8, 'Active', 'CIV', 'CIV 501', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("DAA2", "Design and Analysis of Algorithms", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 8, 'Active', 'CIV', 'CIV 502', 3, 100, 91);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("CG2", "Computer Graphics", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 9, 'Active', 'CIV', 'CIV 503', 3, 100, 85);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("AI2", "Artificial Intelligence", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 9, 'Active', 'CIV', 'CIV 504', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ML2", "Machine Learning", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 10, 'Active', 'CIV', 'CIV 505', 3, 100, 23);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("OS2", "Operating Systems", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 10, 'Active', 'CIV', 'CIV 506', 3, 100, 11);


insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ALDA3", "Analytics of data and Data pre-processing", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 11, 'Active', 'EEE', 'EEE 501', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("DAA3", "Design and Analysis of Algorithms", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 11, 'Active', 'EEE', 'EEE 502', 3, 100, 91);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("CG3", "Computer Graphics", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 12, 'Active', 'EEE', 'EEE 503', 3, 100, 85);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("AI3", "Artificial Intelligence", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 12, 'Active', 'EEE', 'EEE 504', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ML3", "Machine Learning", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 13, 'Active', 'EEE', 'EEE 505', 3, 100, 23);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("OS3", "Operating Systems", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 13, 'Active', 'EEE', 'EEE 506', 3, 100, 11);

insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ALDA4", "Analytics of data and Data pre-processing", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 14, 'Active', 'ECE', 'ECE 501', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("DAA4", "Design and Analysis of Algorithms", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 14, 'Active', 'ECE', 'ECE 502', 3, 100, 91);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("CG4", "Computer Graphics", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 15, 'Active', 'ECE', 'ECE 503', 3, 100, 85);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("AI4", "Artificial Intelligence", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 15, 'Active', 'ECE', 'ECE 504', 3, 100, 1);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("ML4", "Machine Learning", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 16, 'Active', 'ECE', 'ECE 505', 3, 100, 23);
insert into course(title, description, location, timings, instructor_id, status, department, code, credits, total_strength, current_strength) values("OS4", "Operating Systems", 'EB-2 Room 101', '1:30 PM to 2:45 PM', 16, 'Active', 'ECE', 'ECE 506', 3, 100, 11);
